//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_kaspi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int ID { get; set; }
        public Nullable<int> AgrID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Agreement Agreement { get; set; }
    }
}
